2.0 preview
PolymerElements/paper-slider pull request #174
Opened 2017-03-02 04:12 UTC by e111077

DO NOT MERGE

2017-03-30 23:58 UTC, notwaldorf requested changes

2017-03-30 23:58 UTC, notwaldorf commented on demo/index.html
> -    document.addEventListener('WebComponentsReady', function() {
uhoh, did this really change? should we fix this in `webcomponents.js`?

2017-03-30 23:58 UTC, notwaldorf commented on paper-slider.html
> +        /*transition: left 0.08s ease;*/
soooooo why the extra 1s?

2017-03-30 23:58 UTC, notwaldorf commented on paper-slider.html
> +          console.log('knobend false');
✂️

2017-03-30 23:58 UTC, notwaldorf commented on paper-slider.html
> +          console.log('bardown false');
✂️

2017-03-30 23:58 UTC, notwaldorf commented on test/a11y.html
> +      // a11ySuite('trivialSlider');
still broken? can you double check, pls? (some changes were merged in a11ySuite)

2017-03-31 03:24 UTC, e111077 commented on paper-slider.html
> +        /*transition: left 0.08s ease;*/
this is awkward. I'm pretty sure this was for testing...

2017-03-31 03:26 UTC, e111077 commented on demo/index.html
> -    document.addEventListener('WebComponentsReady', function() {
yupppp

2017-03-31 03:26 UTC, e111077 commented on paper-slider.html
> +          console.log('bardown false');
butts

2017-03-31 03:27 UTC, e111077 commented on paper-slider.html
> +          console.log('knobend false');
double butts

2017-03-31 03:27 UTC, e111077 commented on test/a11y.html
> +      // a11ySuite('trivialSlider');
no longer borked

2017-04-04 00:35 UTC, e111077 commented
@notwaldorf done did the things. Tests fail because WCT hates me and `.restore` and stuff

2017-04-04 23:27 UTC, notwaldorf approved these changes

2017-04-04 23:27 UTC, notwaldorf commented
@e111077 i'll investigate this document -> window change, but this is 👍  otherwise

2017-05-12 22:23 UTC, merged